version: '3'

services:
  master:
    build: ./image
    ports:
      - 8080:8080
      - 7077:7077
    command: spark-class org.apache.spark.deploy.master.Master --host 0.0.0.0
  worker:
    build: ./image
    depends_on: [master]
    command: spark-class org.apache.spark.deploy.worker.Worker spark://master:7077
  jupyter:
    build: ./jupyter
    depends_on: [master]
    ports:
      - 8888:8888
    volumes:
     - ./:/w
    working_dir: /w
