version: '3'

services:
  namenode:
    build: ./image
    command: /start-namenode.sh hdfs://namenode -Ddfs.replication=1
    volumes:
      - /tmp/hadoop-root
    ports:
      - 9870:9870
  datanode:
    build: ./image
    command: /start-datanode.sh hdfs://namenode -Ddfs.replication=1
    volumes:
      - /tmp/hadoop-root
