version: '3'

services:
  storage:
    image: minio/minio
    volumes:
     - /export
    ports:
     - 9000:9000
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: miniominio
      MINIO_HTTP_TRACE: /dev/stdout
    command: server /export
