version: '3'
services:
  db:
    # image: cockroachdb/cockroach:v19.1.2
    build:
      context: cockroach.image
    environment:
      POSTGRES_USER: sbtest
      POSTGRES_PASSWORD: sbtest
      POSTGRES_DB: sbtest
    command: start --insecure
