version: '3'
services:
  pd0:
    image: pingcap/pd:latest
    volumes:
     - ./tidb/pd.toml:/pd.toml:ro
     - /data
    command:
     - --name=pd0
     - --client-urls=http://0.0.0.0:2379
     - --peer-urls=http://0.0.0.0:2380
     - --advertise-client-urls=http://pd0:2379
     - --advertise-peer-urls=http://pd0:2380
     - --initial-cluster=pd0=http://pd0:2380
     - --data-dir=/data/pd0
     - --config=/pd.toml
  tikv1:
    image: pingcap/tikv:latest
    volumes:
     - ./tidb/tikv.toml:/tikv.toml:ro
     - /data
    command:
     - --addr=0.0.0.0:20160
     - --advertise-addr=tikv1:20160
     - --data-dir=/data/tikv
     - --pd=pd0:2379
     - --config=/tikv.toml
    depends_on: [pd0]
  tikv2:
    image: pingcap/tikv:latest
    volumes:
     - ./tidb/tikv.toml:/tikv.toml:ro
     - /data
    command:
     - --addr=0.0.0.0:20160
     - --advertise-addr=tikv2:20160
     - --data-dir=/data/tikv
     - --pd=pd0:2379
     - --config=/tikv.toml
    depends_on: [pd0]
  tikv3:
    image: pingcap/tikv:latest
    volumes:
     - ./tidb/tikv.toml:/tikv.toml:ro
     - /data
    command:
     - --addr=0.0.0.0:20160
     - --advertise-addr=tikv3:20160
     - --data-dir=/data/tikv
     - --pd=pd0:2379
     - --config=/tikv.toml
    depends_on: [pd0]
  db:
    image: pingcap/tidb:latest
    ports:
     - "4000:4000"
     - "10080:10080"
    volumes:
     - ./tidb/tidb.toml:/tidb.toml:ro
    command:
     - --store=tikv
     - --path=pd0:2379
     - --config=/tidb.toml
    depends_on: [tikv0]
